"""
Mock data generator
===================
Builds the four "system exports" that Agora ingests: an ERP product list, a WMS
stock file, a pricing export and a supplier registry. Every value comes from one
seed, so the files can be regenerated byte for byte.

Run from the repository root:  python tools/generate_mock_data.py
"""

import csv
import json
import logging
import random
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

SEED = 20260905
RAW_DIR = Path(__file__).resolve().parent.parent / "data" / "raw"

BRANDS = ["Elektra", "Voltera", "Nordion", "Kyma", "Delta Line"]
WAREHOUSES = ["ATH-01", "ATH-02", "THE-01", "PAT-01"]
UPDATED_DATES = ["2026-07-14", "2026-08-03", "2026-08-21", "2026-09-01"]

SUPPLIERS = [
    ("SUP-01", "Ionia Electric", 3, 0.96),
    ("SUP-02", "Aegean Supplies", 7, 0.88),
    ("SUP-03", "Balkan Cables", 14, 0.74),
    ("SUP-04", "Hellenic Power Systems", 5, 0.92),
]

# 226 SKUs in total (small enough that the CSVs can still be read by the eye)
CATEGORY_SIZES = {"PWR": 58, "DAT": 46, "PSU": 34, "UPS": 28, "SWT": 30, "CON": 30}
CATEGORY_NAMES = {
    "PWR": "POWER",
    "DAT": "DATA",
    "PSU": "PSU",
    "UPS": "UPS",
    "SWT": "NETWORK",
    "CON": "CONNECTORS",
}
PRICE_BANDS = {
    "PWR": (8.0, 180.0),
    "DAT": (4.5, 95.0),
    "PSU": (35.0, 240.0),
    "UPS": (95.0, 1450.0),
    "SWT": (45.0, 890.0),
    "CON": (2.5, 68.0),
}


def _specs(code: str, rng: random.Random) -> dict:
    """Plausible technical specs for one product of this category."""
    if code == "PWR":
        return {
            "cores": rng.choice([3, 5]),
            "section_mm": rng.choice([1.5, 2.5, 4.0, 6.0]),
            "length_m": rng.choice([5, 10, 15, 20, 25, 30, 50]),
            "watt": rng.choice([750, 1000, 1500, 2200, 3000]),
            "ip_rating": rng.choice(["IP44", "IP54", "IP67"]),
        }
    if code == "DAT":
        return {
            "standard": rng.choice(["CAT5e", "CAT6", "CAT6a", "CAT7"]),
            "shielding": rng.choice(["UTP", "FTP", "S/FTP"]),
            "length_m": rng.choice([1, 3, 5, 10, 15, 20, 30]),
        }
    if code == "PSU":
        return {
            "watt": rng.choice([450, 550, 650, 750, 850, 1000]),
            "efficiency": rng.choice(["80+ Bronze", "80+ Gold", "80+ Platinum"]),
            "form_factor": rng.choice(["ATX", "SFX"]),
        }
    if code == "UPS":
        va = rng.choice([650, 1000, 1500, 2200, 3000])
        return {
            "va": va,
            "watt": int(va * 0.6),
            "topology": rng.choice(["line-interactive", "online"]),
            "autonomy_min": rng.choice([8, 12, 20, 35]),
        }
    if code == "SWT":
        return {
            "ports": rng.choice([8, 16, 24, 48]),
            "speed_mbps": rng.choice([100, 1000, 2500]),
            "poe": rng.choice([True, False]),
            "managed": rng.choice([True, False]),
        }
    return {
        "connector_type": rng.choice(["CEE", "Schuko", "IEC C13", "IEC C19"]),
        "amperage": rng.choice([16, 32, 63]),
        "ip_rating": rng.choice(["IP44", "IP67"]),
    }


def _length(metres: int, rng: random.Random) -> str:
    """Three ways of writing the same length, because three systems typed it."""
    return rng.choice([f"{metres}m", f"{metres} μ.", f"{metres * 100}cm"])


def _watt(watt: int, rng: random.Random) -> str:
    if watt >= 1000 and watt % 1000 == 0 and rng.random() < 0.4:
        return f"{watt // 1000}kW"
    return f"{watt}W"


def _describe(code: str, s: dict, rng: random.Random) -> str:
    """The Greek description as the ERP holds it, with the specs inside the text."""
    if code == "PWR":
        return "Καλώδιο ρεύματος {}x{}mm {} {} {} εξωτερικού χώρου".format(
            s["cores"],
            s["section_mm"],
            _length(s["length_m"], rng),
            _watt(s["watt"], rng),
            s["ip_rating"],
        )
    if code == "DAT":
        return "Καλώδιο δικτύου {} {} {}".format(
            s["standard"], s["shielding"], _length(s["length_m"], rng)
        )
    if code == "PSU":
        return "Τροφοδοτικό {} {} {}".format(
            _watt(s["watt"], rng), s["efficiency"], s["form_factor"]
        )
    if code == "UPS":
        return "UPS {} {}VA / {} αυτονομία {} λεπτά".format(
            s["topology"], s["va"], _watt(s["watt"], rng), s["autonomy_min"]
        )
    if code == "SWT":
        extras = " PoE" if s["poe"] else ""
        extras += " managed" if s["managed"] else " unmanaged"
        return "Switch {} θυρών {}Mbps{}".format(s["ports"], s["speed_mbps"], extras)
    return "Ρευματολήπτης {} {}A {}".format(
        s["connector_type"], s["amperage"], s["ip_rating"]
    )


def build_catalog(rng: random.Random) -> list[dict]:
    """Build the whole product catalogue.

    Args:
        rng: Seeded generator, so the same seed gives the same catalogue.

    Returns:
        One dict per SKU, carrying the identifiers, the Greek description and the
        commercial fields the four exports draw from.
    """
    catalog = []
    for code, size in CATEGORY_SIZES.items():
        for n in range(size):
            specs = _specs(code, rng)
            catalog.append(
                {
                    "sku": f"{code}-{1000 + n}",
                    "code": code,
                    "category": CATEGORY_NAMES[code],
                    "brand": rng.choice(BRANDS),
                    "description": _describe(code, specs, rng),
                    "price": round(rng.uniform(*PRICE_BANDS[code]), 2),
                    "stock": rng.choice([0, 0, 4, 12, 25, 40, 80, 150]),
                    "warehouse": rng.choice(WAREHOUSES),
                    "supplier": rng.choice(SUPPLIERS)[0],
                }
            )
    return catalog


def _erp_code(sku: str, rng: random.Random) -> str:
    roll = rng.random()
    if roll < 0.12:
        return sku.replace("-", "").lower()
    if roll < 0.20:
        return "  " + sku
    return sku


def write_erp(catalog: list[dict], rng: random.Random) -> None:
    """Write the ERP product export, with its duplicates and its one unusable row."""
    rows = [
        (_erp_code(p["sku"], rng), p["description"], p["category"], p["brand"], "ΤΕΜ")
        for p in catalog
    ]

    for p in (catalog[7], catalog[131]):
        rows.append(
            (p["sku"], p["description"] + " ", p["category"], p["brand"], "τεμ")
        )

    rows.append(("", "Καλώδιο ρεύματος 3x2.5mm 20m", "POWER", "Kyma", "ΤΕΜ"))

    with open(RAW_DIR / "erp_products.csv", "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["item_code", "description", "cat", "brand", "unit"])
        writer.writerows(rows)
    logger.info("erp_products.csv — %d rows", len(rows))


def write_wms(catalog: list[dict], rng: random.Random) -> None:
    """Write the warehouse stock export. Not every SKU is registered in it."""
    rows = []
    for p in catalog:
        sku = p["sku"].replace("-", " ") if rng.random() < 0.25 else p["sku"]
        rows.append((sku, p["stock"], p["warehouse"]))

    missing = {catalog[i]["sku"] for i in (3, 61, 104, 158, 199)}
    rows = [r for r in rows if r[0].replace(" ", "-") not in missing]

    rows.append((catalog[12]["sku"], "-", "ATH-01"))

    with open(RAW_DIR / "wms_stock.csv", "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f, delimiter=";")
        writer.writerow(["sku", "qty_available", "warehouse"])
        writer.writerows(rows)
    logger.info("wms_stock.csv — %d rows, %d SKUs missing", len(rows), len(missing))


def _price_text(value: float, index: int) -> str:
    """The same number as the ERP writes it, as the shop writes it, as the export writes it."""
    if index % 3 == 0:
        return f"€ {value:.2f}".replace(".", ",")
    if index % 3 == 1:
        return f"{value:.2f}"
    return f"{value:.2f} EUR".replace(".", ",")


def write_pricing(catalog: list[dict], rng: random.Random) -> None:
    """Write the pricing export, cycling through the three price formats."""
    rows = []
    for i, p in enumerate(catalog):
        code = p["sku"] + " " if rng.random() < 0.15 else p["sku"]
        rows.append(
            (code, _price_text(p["price"], i), "EUR", rng.choice(UPDATED_DATES))
        )

    rows.append((catalog[45]["sku"], "N/A", "EUR", "2026-08-03"))
    rows.append((catalog[77]["sku"], "-12,50", "EUR", "2026-08-21"))

    with open(RAW_DIR / "pricing.csv", "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["product_code", "list_price", "currency", "updated_at"])
        writer.writerows(rows)
    logger.info("pricing.csv — %d rows", len(rows))


def write_suppliers(catalog: list[dict]) -> None:
    """Write the supplier registry: one entry per supplier, each listing its SKUs."""
    registry = []
    for code, name, lead_time, reliability in SUPPLIERS:
        skus = [p["sku"] for p in catalog if p["supplier"] == code]
        registry.append(
            {
                "supplier_code": code,
                "name": name,
                "lead_time_days": lead_time,
                "reliability_score": reliability,
                "supplies": skus,
            }
        )

    with open(RAW_DIR / "suppliers.json", "w", encoding="utf-8") as f:
        json.dump({"suppliers": registry}, f, ensure_ascii=False, indent=2)
        f.write("\n")
    logger.info("suppliers.json — %d suppliers", len(registry))


def main() -> None:
    RAW_DIR.mkdir(parents=True, exist_ok=True)
    rng = random.Random(SEED)

    catalog = build_catalog(rng)
    logger.info(
        "catalogue built — %d SKUs over %d categories",
        len(catalog),
        len(CATEGORY_SIZES),
    )

    write_erp(catalog, rng)
    write_wms(catalog, rng)
    write_pricing(catalog, rng)
    write_suppliers(catalog)


if __name__ == "__main__":
    main()
