"""
Mock data generator
===================
Builds the four "system exports" that Agora ingests: an ERP product list, a WMS
stock file, a pricing export and a supplier registry. What a product of each category
looks like is decided by the record builder in the catalogue service; this script only
decides how the four systems disagree about writing it down.

Every value comes from one seed, so the files can be regenerated byte for byte.

Run from the repository root:  python -m tools.generate_mock_data
"""

import csv
import json
import logging
import random
from pathlib import Path

from services.data_service.categories import (
    SKU_PREFIXES,
    Category,
    SupplierCode,
    Warehouse,
)
from services.data_service.generation.builder import (
    DEFAULT_BRANDS,
    QUANTITIES,
    SKU_START,
    build_specs,
    describe,
    price_for,
)

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

SEED = 20260905
RAW_DIR = Path(__file__).resolve().parent.parent / "data" / "raw"

UPDATED_DATES = ["2026-07-14", "2026-08-03", "2026-08-21", "2026-09-01"]

SUPPLIERS = [
    (SupplierCode.SUP_01, "Ionia Electric", 3, 0.96),
    (SupplierCode.SUP_02, "Aegean Supplies", 7, 0.88),
    (SupplierCode.SUP_03, "Balkan Cables", 14, 0.74),
    (SupplierCode.SUP_04, "Hellenic Power Systems", 5, 0.92),
]

# 226 SKUs in total (small enough that the CSVs can still be read by the eye)
CATEGORY_SIZES = {
    Category.POWER: 58,
    Category.DATA: 46,
    Category.PSU: 34,
    Category.UPS: 28,
    Category.NETWORK: 30,
    Category.CONNECTORS: 30,
}


# ── The product universe ─────────────────────────────────────────────────────


def build_catalog(rng: random.Random) -> list[dict]:
    """Build the whole product catalogue.

    Args:
        rng: Seeded generator, so the same seed gives the same catalogue.

    Returns:
        One dict per SKU, carrying the identifiers, the Greek description and the
        commercial fields the four exports draw from.
    """
    catalog = []
    for category, size in CATEGORY_SIZES.items():
        for n in range(size):
            specs = build_specs(category, rng)
            catalog.append(
                {
                    "sku": f"{SKU_PREFIXES[category]}-{SKU_START + n}",
                    "category": category,
                    "brand": rng.choice(DEFAULT_BRANDS),
                    "description": describe(category, specs, rng),
                    "price": price_for(category, rng),
                    "stock": rng.choice(QUANTITIES),
                    "warehouse": rng.choice(list(Warehouse)),
                    "supplier": rng.choice(SUPPLIERS)[0],
                }
            )
    return catalog


# ── The four exports ─────────────────────────────────────────────────────────


def _erp_code(sku: str, rng: random.Random) -> str:
    roll = rng.random()
    if roll < 0.12:
        return sku.replace("-", "").lower()
    if roll < 0.20:
        return "  " + sku
    return sku


def write_erp(catalog: list[dict], rng: random.Random) -> None:
    """Write the ERP product export, with its duplicates and its one unusable row."""
    rows = [
        (_erp_code(p["sku"], rng), p["description"], p["category"], p["brand"], "ΤΕΜ")
        for p in catalog
    ]

    for p in (catalog[7], catalog[131]):
        rows.append(
            (p["sku"], p["description"] + " ", p["category"], p["brand"], "τεμ")
        )

    rows.append(("", "Καλώδιο ρεύματος 3x2.5mm 20m", "POWER", "Kyma", "ΤΕΜ"))

    with open(RAW_DIR / "erp_products.csv", "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["item_code", "description", "cat", "brand", "unit"])
        writer.writerows(rows)
    logger.info("erp_products.csv — %d rows", len(rows))


def write_wms(catalog: list[dict], rng: random.Random) -> None:
    """Write the warehouse stock export. Not every SKU is registered in it."""
    rows = []
    for p in catalog:
        sku = p["sku"].replace("-", " ") if rng.random() < 0.25 else p["sku"]
        rows.append((sku, p["stock"], p["warehouse"]))

    missing = {catalog[i]["sku"] for i in (3, 61, 104, 158, 199)}
    rows = [r for r in rows if r[0].replace(" ", "-") not in missing]

    rows.append((catalog[12]["sku"], "-", "ATH-01"))

    with open(RAW_DIR / "wms_stock.csv", "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f, delimiter=";")
        writer.writerow(["sku", "qty_available", "warehouse"])
        writer.writerows(rows)
    logger.info("wms_stock.csv — %d rows, %d SKUs missing", len(rows), len(missing))


def _price_text(value: float, index: int) -> str:
    """The same number as the ERP writes it, as the shop writes it, as the export writes it."""
    if index % 3 == 0:
        return f"€ {value:.2f}".replace(".", ",")
    if index % 3 == 1:
        return f"{value:.2f}"
    return f"{value:.2f} EUR".replace(".", ",")


def write_pricing(catalog: list[dict], rng: random.Random) -> None:
    """Write the pricing export, cycling through the three price formats."""
    rows = []
    for i, p in enumerate(catalog):
        code = p["sku"] + " " if rng.random() < 0.15 else p["sku"]
        rows.append(
            (code, _price_text(p["price"], i), "EUR", rng.choice(UPDATED_DATES))
        )

    rows.append((catalog[45]["sku"], "N/A", "EUR", "2026-08-03"))
    rows.append((catalog[77]["sku"], "-12,50", "EUR", "2026-08-21"))

    with open(RAW_DIR / "pricing.csv", "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["product_code", "list_price", "currency", "updated_at"])
        writer.writerows(rows)
    logger.info("pricing.csv — %d rows", len(rows))


def write_suppliers(catalog: list[dict]) -> None:
    """Write the supplier registry: one entry per supplier, each listing its SKUs."""
    registry = []
    for code, name, lead_time, reliability in SUPPLIERS:
        skus = [p["sku"] for p in catalog if p["supplier"] == code]
        registry.append(
            {
                "supplier_code": code,
                "name": name,
                "lead_time_days": lead_time,
                "reliability_score": reliability,
                "supplies": skus,
            }
        )

    with open(RAW_DIR / "suppliers.json", "w", encoding="utf-8") as f:
        json.dump({"suppliers": registry}, f, ensure_ascii=False, indent=2)
        f.write("\n")
    logger.info("suppliers.json — %d suppliers", len(registry))


def main() -> None:
    RAW_DIR.mkdir(parents=True, exist_ok=True)
    rng = random.Random(SEED)

    catalog = build_catalog(rng)
    logger.info(
        "catalogue built — %d SKUs over %d categories",
        len(catalog),
        len(CATEGORY_SIZES),
    )

    write_erp(catalog, rng)
    write_wms(catalog, rng)
    write_pricing(catalog, rng)
    write_suppliers(catalog)


if __name__ == "__main__":
    main()
